language: python
python: 3.5
branches:
  only:
  - master
# before_install:
install: 
- pip install requests
- pip install pytest
- pip install pytest-cov
- pip install codecov
script:
- py.test --cov=./
after_success:
- codecov